# Generated by Django 4.2.1 on 2023-05-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop_s',
            field=models.ManyToManyField(blank=True, related_name='categorie', to='APIbackend.shop', verbose_name='Магазины'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='shops',
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ForeignKey(blank=True, default='my_default_value', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='APIbackend.shop', verbose_name='Магазины'),
        ),
    ]
